# Generated by Django 2.2 on 2021-05-24 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 5, 24), null=True),
        ),
    ]
