# Generated by Django 2.2 on 2021-05-24 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_auto_20210524_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 10, 49, 28, 172778), null=True),
        ),
    ]
