# Generated by Django 2.2 on 2021-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0003_auto_20210524_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
